### ISSUE TITLE
Error on loading pretrained weights

### ISSUE THREAD

**Issue by anuragranj** [ClementPinard/DepthNet#1]
I am getting an error on the following.
```python 
depthnet = DepthNet()
weights = torch.load('DepthNet_elu_bn_512.pth.tar')
depthnet.load_state_dict(weights['state_dict'], strict=False)

RuntimeError: While copying the parameter named conv1.0.weight, whose dimensions in the model are torch.Size([32, 6, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 8, 3, 3]).
```
It seems that the DepthNet512 had 8 channels in the first conv layer, which are not reflected in the model class. Is that so?

**Comment by ClementPinard** [comment]
Oh I'm sorry, these models are actually some tries I did using distance from optical center, so basically, I added 2 layers with normalized coordinates ( `(0,0)` being the center)

There has been some mistake that led to them being uploaded instead of regular models, Thanks for the issue, I'm going to fix that.

By the way, adding coordinates doesn't help the model ;)

**Comment by ClementPinard** [comment]
Should be solved now, try re-downloading them !

**Comment by anuragranj** [comment]
Yes. Thanks :)
